<?php

namespace Repository;

/**
 * EntityForumWarnLogsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumWarnLogsRep extends \Doctrine\ORM\EntityRepository
{
}
