<?php

namespace Repository;

/**
 * EntityDirectoryElmRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityDirectoryElmRep extends \Doctrine\ORM\EntityRepository
{
}
