<?php

namespace Repository;

/**
 * EntitySFilesCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFilesCatRep extends \Doctrine\ORM\EntityRepository
{
}
