<?php

namespace Repository;

/**
 * EntityForumMessagesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumMessagesRep extends \Doctrine\ORM\EntityRepository
{
}
