<?php

namespace Repository;

/**
 * EntityForumSearchResultsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumSearchResultsRep extends \Doctrine\ORM\EntityRepository
{
}
