<?php

namespace Repository;

/**
 * EntitySFilesSubcatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFilesSubcatRep extends AbstractEntityRep
{
}
