<?php

namespace Repository;

/**
 * EntityForumMemberExtraRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumMemberExtraRep extends \Doctrine\ORM\EntityRepository
{
}
