<?php

namespace Repository;

/**
 * EntityForumFaqRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumFaqRep extends \Doctrine\ORM\EntityRepository
{
}
