<?php

namespace Repository;

use Entity\EntitySFilesCat;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * EntitySFilesCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFilesCatRep extends AbstractEntityRep
{
}
