<?php

namespace Repository;

/**
 * EntitySFilesDbRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFilesDbRep extends \Doctrine\ORM\EntityRepository
{
}
