<?php

namespace Repository;

/**
 * EntityForumCalendarEventsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumCalendarEventsRep extends \Doctrine\ORM\EntityRepository
{
}
