<?php

namespace Repository;

/**
 * EntitySFaqCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFaqCatRep extends \Doctrine\ORM\EntityRepository
{
}
