<?php

namespace Repository;

/**
 * EntitySMenuItemsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySMenuItemsRep extends \Doctrine\ORM\EntityRepository
{
}
