<?php

namespace Repository;

/**
 * EntityForumQmsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumQmsRep extends \Doctrine\ORM\EntityRepository
{
}
