<?php

namespace Repository;

/**
 * EntitySRefererStatsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySRefererStatsRep extends \Doctrine\ORM\EntityRepository
{
}
