<?php

namespace Repository;

use Entity\EntitySFilesDb;
/**
 * EntitySFilesDbRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFilesDbRep extends \Doctrine\ORM\EntityRepository
{
	public function getCountForReview() {
		return $this->getEntityManager()
			->createQuery('SELECT count(en)
				FROM Entity\EntitySFilesDb en
				WHERE en.show = :show')
					->setParameter('show', "N")
					->getSingleScalarResult();
	}
	
	public function getCountForShow() {
		return $this->getEntityManager()
		->createQuery('SELECT count(en)
				FROM Entity\EntitySFilesDb en
				WHERE en.show = :show')
					->setParameter('show', "Y")
					->getSingleScalarResult();
	}
	
	public function getLastAddedFiles($countRows) {
		return $this->getEntityManager()
			->createQuery('SELECT en FROM Entity\EntitySFilesDb en
					WHERE en.show = :show
					ORDER BY en.id DESC')
			->setParameter('show', 'Y')
			->setMaxResults($countRows)
			->getResult();
	}
	
	public function getMostPopularFiles($countRows) {
		return $this->getEntityManager()
		->createQuery('SELECT en FROM Entity\EntitySFilesDb en
					WHERE en.show = :show
					ORDER BY en.count DESC')
						->setParameter('show', 'Y')
						->setMaxResults($countRows)
						->getResult();
	}
}
