<?php

namespace Repository;

/**
 * EntityForumTitlesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumTitlesRep extends \Doctrine\ORM\EntityRepository
{
}
