<?php

namespace Repository;

/**
 * EntityForumEmoCategoriesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumEmoCategoriesRep extends \Doctrine\ORM\EntityRepository
{
}
