<?php

namespace Repository;

/**
 * EntityForumEmailLogsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumEmailLogsRep extends \Doctrine\ORM\EntityRepository
{
}
