<?php

namespace Repository;

/**
 * EntitySAdminLogsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySAdminLogsRep extends \Doctrine\ORM\EntityRepository
{
}
