<?php

namespace Repository;

/**
 * EntityForumAdminLogsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumAdminLogsRep extends \Doctrine\ORM\EntityRepository
{
}
