<?php

namespace Repository;

/**
 * EntitySAdusersRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySAdusersRep extends \Doctrine\ORM\EntityRepository
{
}
