<?php

namespace Repository;

/**
 * EntityForumSessionsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumSessionsRep extends \Doctrine\ORM\EntityRepository
{
}
