<?php

namespace Repository;

/**
 * EntitySGalleryCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySGalleryCatRep extends \Doctrine\ORM\EntityRepository
{
}
