<?php

namespace Repository;

/**
 * EntityForumTopicsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumTopicsRep extends \Doctrine\ORM\EntityRepository
{
}
