<?php

namespace Repository;

/**
 * EntitySGallerySubcatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySGallerySubcatRep extends \Doctrine\ORM\EntityRepository
{
}
