<?php

namespace Repository;

/**
 * EntityForumPostsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumPostsRep extends \Doctrine\ORM\EntityRepository
{
}
