<?php

namespace Repository;

/**
 * EntityForumAwardsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumAwardsRep extends \Doctrine\ORM\EntityRepository
{
}
