<?php

namespace Repository;

/**
 * EntityForumAdminSessionsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumAdminSessionsRep extends \Doctrine\ORM\EntityRepository
{
}
