<?php

namespace Repository;

/**
 * EntityForumSkinsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumSkinsRep extends \Doctrine\ORM\EntityRepository
{
}
