<?php

namespace Repository;

/**
 * EntityForumLogsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumLogsRep extends \Doctrine\ORM\EntityRepository
{
}
