<?php

namespace Repository;

/**
 * EntitySGalleryImagesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySGalleryImagesRep extends \Doctrine\ORM\EntityRepository
{
}
