<?php

namespace Repository;

/**
 * EntityForumCacheStoreRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumCacheStoreRep extends \Doctrine\ORM\EntityRepository
{
}
