<?php

namespace Repository;

/**
 * EntityForumForumsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumForumsRep extends \Doctrine\ORM\EntityRepository
{
}
