<?php

namespace Repository;

/**
 * EntityForumForumTrackerRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumForumTrackerRep extends \Doctrine\ORM\EntityRepository
{
}
