<?php

namespace Repository;

/**
 * EntityForumChatonlineRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumChatonlineRep extends \Doctrine\ORM\EntityRepository
{
}
