<?php

namespace Repository;

use Entity\EntitySMenuCat;
/**
 * EntitySMenuCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySMenuCatRep extends \Doctrine\ORM\EntityRepository
{
	public function getAllCategories() {
		return $this->getEntityManager()
			->createQuery('SELECT en FROM Entity\EntitySMenuCat en ORDER BY en.poz')
			->getResult();
	}
}
