<?php

namespace Repository;

/**
 * EntityForumModeratorsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumModeratorsRep extends \Doctrine\ORM\EntityRepository
{
}
