<?php

namespace Repository;

use Entity\EntitySPages;

/**
 * EntitySPagesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySPagesRep extends \Doctrine\ORM\EntityRepository
{
	function getOneByName($name) {
		return $this->getEntityManager()
		->createQuery('SELECT en
				FROM Entity\EntitySPages en
				WHERE en.name = :name')
						->setParameter('name', $name)
						->getOneOrNullResult();
	}
}
