<?php

namespace Repository;

/**
 * EntityForumSpiderLogsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumSpiderLogsRep extends \Doctrine\ORM\EntityRepository
{
}
