<?php

namespace Repository;

/**
 * EntityForumChatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumChatRep extends \Doctrine\ORM\EntityRepository
{
}
