<?php

namespace Repository;

use Entity\EntitySFaqCat;
/**
 * EntitySFaqCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFaqCatRep extends AbstractEntityRep
{
	protected $_positionFieldName = 'poz';
	
	public function getCategoriesByPopularity() {
		return $this->getEntityManager()
			->createQuery('SELECT en FROM Entity\EntitySFaqCat en ORDER BY en.count DESC')
			->getResult();
	}
}
