<?php

namespace Repository;

/**
 * EntitySFilesDbRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFilesDbRep extends \Doctrine\ORM\EntityRepository
{
	public function getCountForReview() {
		return $this->getEntityManager()
		->createQuery('SELECT count(en)
				FROM Entity\EntitySFilesDb en
				WHERE en.show = :show')
					->setParameter('show', "N")
					->getSingleScalarResult();
	}
}
