<?php

namespace Repository;

/**
 * EntityForumValidatingRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumValidatingRep extends \Doctrine\ORM\EntityRepository
{
}
