<?php

namespace Repository;

/**
 * EntityForumModeratorLogsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumModeratorLogsRep extends \Doctrine\ORM\EntityRepository
{
}
