<?php

namespace Repository;

/**
 * EntitySMenuCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySMenuCatRep extends \Doctrine\ORM\EntityRepository
{
}
