<?php

namespace Repository;

/**
 * EntityForumContactsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumContactsRep extends \Doctrine\ORM\EntityRepository
{
}
