<?php

namespace Repository;

/**
 * EntityForumCategoriesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumCategoriesRep extends \Doctrine\ORM\EntityRepository
{
}
