<?php

namespace Repository;

/**
 * EntitySFaqDbRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySFaqDbRep extends \Doctrine\ORM\EntityRepository
{
}
