<?php

namespace Repository;

/**
 * EntityForumRegAntispamRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumRegAntispamRep extends \Doctrine\ORM\EntityRepository
{
}
