<?php

namespace Repository;

/**
 * EntitySMailTemplatesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySMailTemplatesRep extends \Doctrine\ORM\EntityRepository
{
}
