<?php

namespace Repository;

/**
 * EntityForumReputationRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumReputationRep extends \Doctrine\ORM\EntityRepository
{
}
