<?php

namespace Repository;

/**
 * EntityForumMacroNameRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumMacroNameRep extends \Doctrine\ORM\EntityRepository
{
}
