<?php

namespace Repository;

/**
 * EntityForumTmplNamesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumTmplNamesRep extends \Doctrine\ORM\EntityRepository
{
}
