<?php

namespace Repository;

/**
 * EntityForumBadwordsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumBadwordsRep extends \Doctrine\ORM\EntityRepository
{
}
