<?php

namespace Repository;

/**
 * EntityForumForumPermsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumForumPermsRep extends \Doctrine\ORM\EntityRepository
{
}
