<?php

namespace Repository;

/**
 * EntityForumPollsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumPollsRep extends \Doctrine\ORM\EntityRepository
{
}
