<?php

namespace Repository;

/**
 * EntityForumSkinTemplatesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumSkinTemplatesRep extends \Doctrine\ORM\EntityRepository
{
}
