<?php

namespace Repository;

/**
 * EntityForumTopicMmodRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumTopicMmodRep extends \Doctrine\ORM\EntityRepository
{
}
