<?php

namespace Repository;

/**
 * EntityForumTrackerRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumTrackerRep extends \Doctrine\ORM\EntityRepository
{
}
