<?php

namespace Repository;

/**
 * EntityForumPfieldsContentRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumPfieldsContentRep extends \Doctrine\ORM\EntityRepository
{
}
