<?php

namespace Repository;

use Entity\EntitySMenuCat;
use Entity\EntitySMenuItems;
/**
 * EntitySMenuCatRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySMenuCatRep extends \Doctrine\ORM\EntityRepository
{
	public function getAllCategories() {
		return $this->getEntityManager()
			->createQuery('SELECT c FROM Entity\EntitySMenuCat c ORDER BY c.poz')
			->getResult();
	}
	
	public function getAllCategoriesWithItems() {
		return $this->getEntityManager()
			->createQuery('SELECT c, i FROM Entity\EntitySMenuCat c LEFT JOIN c.itemsVal i ORDER BY c.poz')
			->getResult();
	}
}
