<?php

namespace Repository;

/**
 * EntityForumReputationBakRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumReputationBakRep extends \Doctrine\ORM\EntityRepository
{
}
