<?php

namespace Repository;

/**
 * EntityForumPfieldsDataRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumPfieldsDataRep extends \Doctrine\ORM\EntityRepository
{
}
