<?php

namespace Repository;

/**
 * EntityDirectoryListRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityDirectoryListRep extends \Doctrine\ORM\EntityRepository
{
}
