<?php

namespace Repository;

/**
 * EntityForumLanguagesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumLanguagesRep extends \Doctrine\ORM\EntityRepository
{
}
