<?php

namespace Repository;

use Entity\EntityForumMembers;
/**
 * EntityForumMembersRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumMembersRep extends \Doctrine\ORM\EntityRepository
{
	public function getMostPosterMember() {
		return $this->getEntityManager()
			->createQuery('SELECT m FROM Entity\EntityForumMembers m ORDER BY m.posts DESC')
			->setMaxResults(1)
			->getSingleResult();;
	}
}
