<?php

namespace Repository;

/**
 * EntitySModulesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySModulesRep extends \Doctrine\ORM\EntityRepository
{
	function getOneByName($name) {
		return $this->getEntityManager()
		->createQuery('SELECT en
				FROM Entity\EntitySModules en
				WHERE en.name = :name')
					->setParameter('name', $name)
					->getOneOrNullResult(); 
	}
}
