<?php

namespace Repository;

/**
 * EntitySCommentsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySCommentsRep extends \Doctrine\ORM\EntityRepository
{
}
