<?php

namespace Repository;

/**
 * EntityForumVotersRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumVotersRep extends \Doctrine\ORM\EntityRepository
{
}
