<?php

namespace Repository;

/**
 * EntityForumStatsRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumStatsRep extends \Doctrine\ORM\EntityRepository
{
}
