<?php

namespace Repository;

/**
 * EntitySImagesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySImagesRep extends \Doctrine\ORM\EntityRepository
{
}
