<?php

namespace Repository;

/**
 * EntitySConfigRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitySConfigRep extends \Doctrine\ORM\EntityRepository
{
}
