<?php

namespace Repository;

/**
 * EntityForumMacroRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumMacroRep extends \Doctrine\ORM\EntityRepository
{
}
