<?php

namespace Repository;

/**
 * EntityForumReputRanksRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumReputRanksRep extends \Doctrine\ORM\EntityRepository
{
}
