<?php

namespace Repository;

/**
 * EntityForumTemplatesRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumTemplatesRep extends \Doctrine\ORM\EntityRepository
{
}
