<?php

namespace Repository;

/**
 * EntityForumCssRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumCssRep extends \Doctrine\ORM\EntityRepository
{
}
