<?php

namespace Repository;

/**
 * EntityForumNamesHistoryRep
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityForumNamesHistoryRep extends \Doctrine\ORM\EntityRepository
{
}
